### ISSUE TITLE
WP5.4 Meta fields are missing

### ISSUE THREAD

**Issue by PrinzMonty** [wielebenwir/commons-booking#183] opened 2020-05-26 15:38 UTC
Hello,

since the last update all meta fields are missing, e.g. address, shortinfo.

I add them now manually in the database.
In the DB as example:

```
meta_key: "commons-booking_location_adress_street"
meta_key: "commons-booking_item_descr"
```

I use the Classic Editor for Wordpress.

**Comment by flegfleg** [comment] 2020-05-26 16:25
Hi, 
that is weird… i cannot reproduce that with WP 4.5.1. 

1. Does the metabox show up? 
2. Are the boxes maybe hidden (see second screen shot)? 
3.  [Can you enable WP_Debug](https://wordpress.org/support/article/debugging-in-wordpress/) and tell me if any errors show up? 

<img width="745" alt="Bildschirmfoto 2020-05-26 um 18 20 50" src="https://user-images.githubusercontent.com/4009931/82925169-abc89880-9f7d-11ea-83c0-cf1cbca8d28b.png">

<img width="1002" alt="Bildschirmfoto 2020-05-26 um 18 22 09" src="https://user-images.githubusercontent.com/4009931/82925398-f5b17e80-9f7d-11ea-8797-f20617ff831f.png">

**Comment by PrinzMonty** [comment] 2020-05-26 16:56
Mm, I'm confused.

![image](https://user-images.githubusercontent.com/4109582/82928464-91dd8480-9f82-11ea-98c2-c013dbe521e0.png)

**Comment by flegfleg** [comment] 2020-05-26 16:59
probably some compatibility issues with other plugins. 
can you create a list of your plugins/environment ([Send System Info is handy](https://github.com/mathetos/send-system-info)) and post them here or send them to florian @ wielebenwir.de ?

**Comment by PrinzMonty** [comment] 2020-05-26 17:11
Oh, come on! Thanks for the tip with the plugins.

The plugin that generated the problem:

https://wordpress.org/plugins/hashbar-wp-notification-bar/

**Comment by flegfleg** [comment] 2020-05-26 17:26
🎉 
I will close this thread now.

**Closed by flegfleg** 2020-05-26 17:26 UTC
